import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { readFileSync } from 'node:fs';
const years=Array.from({length:113},(_,i)=>`<div class="am-picker-col-item ${i===112?'am-picker-col-item-selected':''}">${1900+i}年</div>`).join('');
const dom=new JSDOM(`<body><div class="my-list-item"><div class="header-title">专业</div><div class="am-input-control">需要和毕业证保持一致</div></div>
  <div class="am-picker-popup"><div class="am-picker-col">${years}</div><div class="am-picker-popup-item">确定</div></div>
  <div class="mc-select-popup"><label><input type="radio"/>河源市</label></div></body>`,{runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;
w.HTMLElement.prototype.getBoundingClientRect=()=>({top:0,left:0,right:200,bottom:30,width:200,height:30});
let handler;
w.chrome={runtime:{onMessage:{addListener:fn=>handler=fn},sendMessage:()=>{}}};
w.eval(readFileSync(new URL('../content/content.js',import.meta.url),'utf8'));
const send=msg=>new Promise(resolve=>handler(msg,{},resolve));
let snap=await send({type:'SNAPSHOT_REQUEST'});
const col=snap.elements.find(e=>e.kind==='picker-column');
assert.equal(col.options.length,113);
assert.equal(col.value,'2012年');
assert.ok(col.options.some(o=>o.label==='2003年'));
assert.ok(snap.elements.some(e=>e.label==='专业'&&e.operations.includes('CLICK')));
assert.ok(snap.elements.some(e=>e.role==='radio'&&e.label==='河源市'&&e.context==='popup'));
let dragged=false;
w.document.querySelector('.am-picker-col').addEventListener('mouseup',()=>{
  dragged=true;
  w.document.querySelector('.am-picker-col-item-selected').classList.remove('am-picker-col-item-selected');
  w.document.querySelectorAll('.am-picker-col-item')[103].classList.add('am-picker-col-item-selected');
});
assert.equal((await send({type:'EXECUTE',action:'select',target:col.options[103].index})).ok,true);
assert.ok(dragged);
w.document.body.innerHTML='<input placeholder="背后的字段"><div id="editor" style="position:fixed"><input id="search" placeholder="请输入毕业院校"><div>示例大学</div></div>';
w.document.getElementById('editor').getBoundingClientRect=()=>({top:0,left:0,right:w.innerWidth,bottom:w.innerHeight,width:w.innerWidth,height:w.innerHeight});
w.document.getElementById('search').focus();
snap=await send({type:'SNAPSHOT_REQUEST'});
assert.ok(!snap.elements.some(e=>e.label==='背后的字段'));
assert.ok(snap.elements.some(e=>e.label==='请输入毕业院校'&&e.context==='popup'));
assert.ok(snap.elements.some(e=>e.label==='示例大学'&&e.context==='popup'));
w.document.getElementById('editor').className='searchInputComponent';
w.document.getElementById('search').blur();
snap=await send({type:'SNAPSHOT_REQUEST'});
assert.ok(!snap.elements.some(e=>e.label==='背后的字段'));
assert.ok(snap.elements.some(e=>e.label==='请输入毕业院校'&&e.context==='popup'));
w.document.querySelector('#editor div').style.cursor='pointer';
snap=await send({type:'SNAPSHOT_REQUEST'});
assert.ok(snap.elements.some(e=>e.label==='示例大学'&&e.context==='popup'));
w.document.body.innerHTML='<div id="main" style="position:fixed"><input id="name" placeholder="姓名"><input placeholder="年龄"></div>';
w.document.getElementById('main').getBoundingClientRect=()=>({top:0,left:0,right:w.innerWidth,bottom:w.innerHeight,width:w.innerWidth,height:w.innerHeight});
w.document.getElementById('name').focus();
snap=await send({type:'SNAPSHOT_REQUEST'});
assert.ok(snap.elements.every(e=>e.context!=='popup'));
const nameInput=w.document.getElementById('name');
let syntheticBlur=0;
nameInput.addEventListener('blur',()=>syntheticBlur++);
await send({type:'EXECUTE',action:'type_text',index:snap.elements.find(e=>e.label==='姓名').index,value:'测试'});
assert.equal(nameInput.value,'测试');
assert.equal(syntheticBlur,1);
w.document.body.innerHTML='<input type="date">';
snap=await send({type:'SNAPSHOT_REQUEST'});
assert.equal((await send({type:'EXECUTE',action:'type_text',index:snap.elements[0].index,value:'2026-11'})).dataGap,true);
assert.equal(w.document.querySelector('input').value,'');
w.document.body.innerHTML='<div>语言能力</div><div><div class="my-list-item"><div class="header-title"><span class="icon-bitian"></span>证书</div><input></div><div class="my-button-box"><div class="my-button">保存</div></div></div>';
snap=await send({type:'SNAPSHOT_REQUEST'});
assert.ok(snap.elements.some(e=>e.label==='保存'&&e.role==='button'));
assert.ok(snap.elements.some(e=>e.label==='证书'&&e.required));
w.document.body.innerHTML='<input readonly placeholder="请选择入学时间">';
const dateInput=w.document.querySelector('input');
let focusCount=0;
dateInput.addEventListener('focus',()=>focusCount++);
dateInput.focus=()=>{};
snap=await send({type:'SNAPSHOT_REQUEST'});
await send({type:'EXECUTE',action:'click',index:snap.elements[0].index});
assert.equal(focusCount,1,'后台窗口没有原生焦点事件时补齐一次通知');
dateInput.focus=w.HTMLElement.prototype.focus.bind(dateInput);
dateInput.blur();focusCount=0;
await send({type:'EXECUTE',action:'click',index:snap.elements[0].index});
assert.equal(focusCount,1,'正常 focus 已通知时保持单次事件');
w.document.body.innerHTML='<input placeholder="背景姓名"><div role="dialog"><h3>请选择专业</h3><input placeholder="请输入专业名称"><button>选择</button><button>取消</button></div>';
snap=await send({type:'SNAPSHOT_REQUEST'});
assert.ok(!snap.elements.some(e=>e.label==='背景姓名'));
assert.ok(snap.elements.some(e=>e.label==='请输入专业名称'&&e.context==='popup'));
console.log('✓ 完整年份列、隐藏单选、点击生成输入框、全屏搜索隔离、后台焦点通过');
